from datetime import datetime
import helics as h
from dots_infrastructure.DataClasses import TimeStepInformation, EsdlId, HelicsCalculationInformation, PublicationDescription, SubscriptionDescription
from dots_infrastructure.HelicsFederateHelpers import HelicsSimulationExecutor
from esdl import EnergySystem, ElectricityNetwork
from dots_infrastructure.EsdlHelperFunctions import EsdlHelperFunctions

# This file is generated, DO NOT edit this file!

class NetworkbalancerserviceBase(HelicsSimulationExecutor):

    def __init__(self):
        super().__init__()
        self.esdl_obj_mapping : dict[EsdlId, ElectricityNetwork]= {}

        
        # Calculation: network_dispatch
        self.network_dispatch_period_seconds = 900
        network_dispatch_inputs = [
        
            SubscriptionDescription(esdl_type="ElectricityDemand", 
                                    input_name="demand_power_w", 
                                    input_unit="W", 
                                    input_type=h.HelicsDataType.DOUBLE),
        ]
        network_dispatch_outputs = [
        
            PublicationDescription(global_flag=True, 
                                    esdl_type="ElectricityNetwork",
                                    output_name="bess_allocation_w",
                                    output_unit="W", 
                                    data_type=h.HelicsDataType.DOUBLE),
            PublicationDescription(global_flag=True, 
                                    esdl_type="ElectricityNetwork",
                                    output_name="grid_allocation_w",
                                    output_unit="W", 
                                    data_type=h.HelicsDataType.DOUBLE),
        ]
        network_dispatch_information = HelicsCalculationInformation(
            time_period_in_seconds=900,
            offset=0, 
            uninterruptible=False, 
            wait_for_current_time_update=False, 
            terminate_on_error=True, 
            calculation_name="network_dispatch", 
            inputs=network_dispatch_inputs, 
            outputs=network_dispatch_outputs, 
            calculation_function=self.network_dispatch
        )
        self.add_calculation(network_dispatch_information)

    def init_calculation_service(self, energy_system: EnergySystem):
        all_esdl_objs = EsdlHelperFunctions.get_all_esdl_objects_from_type(energy_system.eAllContents(), ElectricityNetwork)
        for esdl_obj in all_esdl_objs:
            if hasattr(esdl_obj, "id"):
                self.esdl_obj_mapping[esdl_obj.id] = esdl_obj

    
    def network_dispatch(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        pass
    